services:
  accounts:
    image: "educavalcantedev/accounts:s4"
    container_name: accounts-ms
    ports:
      - "8080:8080"
    deploy:
      resources:
        limits:
          memory: 500m
    networks:
      - eazybank
  cards:
    image: "educavalcantedev/cards:s4"
    container_name: cards-ms
    ports:
      - "9010:9010"
    deploy:
      resources:
        limits:
          memory: 500m
    networks:
      - eazybank
  loans:
    image: "educavalcantedev/loans:s4"
    container_name: loans-ms
    ports:
      - "8090:8090"
    deploy:
      resources:
        limits:
          memory: 500m
    networks:
      - eazybank
networks:
  eazybank:
    driver: "bridge"